
CREATE TABLE `coherent-bliss-275820.dezoomcamp.ods_football_fixtures`
(
  fixture_id                INT,
  fixture_referee           STRING,
  fixture_timezone          STRING,
  fixture_date              TIMESTAMP,
  fixture_timestamp         INT,
  fixture_periods_first     FLOAT64,
  fixture_periods_second    FLOAT64,
  fixture_venue_id          INT,
  fixture_venue_name        STRING,
  fixture_venue_city        STRING,
  fixture_status_long       STRING,
  fixture_status_short      STRING,
  fixture_status_elapsed    FLOAT64,
  league_id                 INT,
  league_name               STRING,
  league_country            STRING,
  league_logo               STRING,
  league_flag               STRING,
  league_season             INT,
  league_round              STRING,
  teams_home_id             INT,
  teams_home_name           STRING,
  teams_home_logo           STRING,
  teams_home_winner         BOOL,
  teams_away_id             INT,
  teams_away_name           STRING,
  teams_away_logo           STRING,
  teams_away_winner         BOOL,
  goals_home                INT,
  goals_away                INT,
  score_halftime_home       INT,
  score_halftime_away       INT,
  score_fulltime_home       INT,
  score_fulltime_away       INT,
  score_extratime_home      INT,
  score_extratime_away      INT,
  score_penalty_home        INT,
  score_penalty_away        INT,
)
PARTITION BY DATE(fixture_date)
CLUSTER BY league_name;